import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";
import StoreProvider from "./StoreProvider";
import { cookies } from 'next/headers'

export const dynamic = 'force-dynamic';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const user = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/user-info`, {
    credentials: 'include',
    headers: { cookie: cookieStore.toString(),},
  }).then(res => res.ok ? res.json() : null);

  console.log('response fetch user info: ', user)

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased min-h-screen`}>
          <StoreProvider user={user}>
            <Header />
            <main className=" flex flex-1">
              {children}
            </main>
          </StoreProvider>
      </body>
    </html>
  );
}
